const palette = {
  sage: "#7BAE7F",
  sageDark: "#5A8F5E",
  sageLight: "#E8F5E9",
  teal: "#26A69A",
  tealDark: "#00897B",
  tealLight: "#E0F7FA",
  cream: "#FFFDF5",
  warmWhite: "#FFFFFF",
  sand: "#FFF3E0",
  coral: "#FF8A80",
  lavender: "#B39DDB",
  sky: "#81D4FA",
  amber: "#FFD54F",
  charcoal: "#2D3436",
  darkBg: "#F5F7FA",
  darkCard: "#FFFFFF",
  darkSurface: "#EDF2F7",
};

export default {
  light: {
    text: "#1A202C",
    textSecondary: "#4A5568",
    textTertiary: "#A0AEC0",
    background: "#FFFFFF",
    card: "#FFFFFF",
    cardBorder: "#E2E8F0",
    tint: "#26A69A",
    tintDark: "#00897B",
    tabIconDefault: "#CBD5E0",
    tabIconSelected: "#26A69A",
    sage: palette.sage,
    sageDark: palette.sageDark,
    sageLight: "#F0FFF4",
    tealLight: "#E0F7FA",
    cream: "#FFFDF5",
    sand: "#FFF3E0",
    coral: palette.coral,
    lavender: palette.lavender,
    sky: palette.sky,
    amber: palette.amber,
    moodHappy: "#66BB6A",
    moodGood: "#81C784",
    moodNeutral: "#FFD54F",
    moodSad: "#FF8A65",
    moodStressed: "#EF5350",
  },
  dark: {
    text: "#1A202C",
    textSecondary: "#4A5568",
    textTertiary: "#A0AEC0",
    background: "#F7FAFC",
    card: "#FFFFFF",
    cardBorder: "#E2E8F0",
    tint: "#26A69A",
    tintDark: "#00897B",
    tabIconDefault: "#CBD5E0",
    tabIconSelected: "#26A69A",
    sage: palette.sage,
    sageDark: palette.sageDark,
    sageLight: "#F0FFF4",
    tealLight: "#E0F7FA",
    cream: "#FFFDF5",
    sand: "#FFF3E0",
    coral: palette.coral,
    lavender: palette.lavender,
    sky: palette.sky,
    amber: palette.amber,
    moodHappy: "#66BB6A",
    moodGood: "#81C784",
    moodNeutral: "#FFD54F",
    moodSad: "#FF8A65",
    moodStressed: "#EF5350",
  },
};
