const palette = {
  sage: "#7BAE7F",
  sageDark: "#5A8F5E",
  sageLight: "#E8F5E9",
  teal: "#4DB6AC",
  tealDark: "#00897B",
  tealLight: "#E0F2F1",
  cream: "#FFF8E7",
  warmWhite: "#FAFAF5",
  sand: "#F5E6D3",
  coral: "#FF8A80",
  lavender: "#B39DDB",
  sky: "#81D4FA",
  amber: "#FFD54F",
  charcoal: "#2D3436",
  darkBg: "#1A1A2E",
  darkCard: "#16213E",
  darkSurface: "#0F3460",
};

export default {
  light: {
    text: "#2D3436",
    textSecondary: "#636E72",
    textTertiary: "#B2BEC3",
    background: palette.warmWhite,
    card: "#FFFFFF",
    cardBorder: "#E8ECF0",
    tint: palette.teal,
    tintDark: palette.tealDark,
    tabIconDefault: "#B2BEC3",
    tabIconSelected: palette.teal,
    sage: palette.sage,
    sageDark: palette.sageDark,
    sageLight: palette.sageLight,
    tealLight: palette.tealLight,
    cream: palette.cream,
    sand: palette.sand,
    coral: palette.coral,
    lavender: palette.lavender,
    sky: palette.sky,
    amber: palette.amber,
    moodHappy: "#66BB6A",
    moodGood: "#81C784",
    moodNeutral: "#FFD54F",
    moodSad: "#FF8A65",
    moodStressed: "#EF5350",
  },
  dark: {
    text: "#E8ECF0",
    textSecondary: "#A0AEC0",
    textTertiary: "#636E72",
    background: palette.darkBg,
    card: palette.darkCard,
    cardBorder: "#2A2A4A",
    tint: palette.teal,
    tintDark: palette.tealDark,
    tabIconDefault: "#636E72",
    tabIconSelected: palette.teal,
    sage: palette.sage,
    sageDark: palette.sageDark,
    sageLight: "#1B3B2A",
    tealLight: "#0A2E2A",
    cream: "#2A2520",
    sand: "#3A2E20",
    coral: palette.coral,
    lavender: palette.lavender,
    sky: palette.sky,
    amber: palette.amber,
    moodHappy: "#66BB6A",
    moodGood: "#81C784",
    moodNeutral: "#FFD54F",
    moodSad: "#FF8A65",
    moodStressed: "#EF5350",
  },
};
